// Auto-generated by scripts/sync-demo-cases.mjs
export const DEMO_CASE_FILES = [
  "demo-cases/case-01.md",
  "demo-cases/case-02.md",
  "demo-cases/case-03.md",
  "demo-cases/case-04.md",
  "demo-cases/case-05.md",
  "demo-cases/case-06.md"
] as const;
